[package]
name = "bevy_scene2"
version = "0.17.2"
edition = "2024"

[dependencies]
bevy_scene2_macros = { path = "macros", version = "0.17.2" }

bevy_app = { path = "../bevy_app", version = "0.17.2" }
bevy_asset = { path = "../bevy_asset", version = "0.17.2" }
bevy_derive = { path = "../bevy_derive", version = "0.17.2" }
bevy_ecs = { path = "../bevy_ecs", version = "0.17.2" }
bevy_log = { path = "../bevy_log", version = "0.17.2" }
bevy_platform = { path = "../bevy_platform", version = "0.17.2" }
bevy_reflect = { path = "../bevy_reflect", version = "0.17.2" }
bevy_utils = { path = "../bevy_utils", version = "0.17.2" }

indexmap = { version = "2.5.0", default-features = false }
variadics_please = "1.0"

[lints]
workspace = true
